name: ${name}
main: ${group}.ShopPlugin
version: ${version}
api-version: 1.21
description: GUI магазин для предметов
author: FlyAwayMaking
website: https://github.com/flyawaymaking
depend: [CoinsEngine]
softdepend:
  - PlaceholderAPI

commands:
  dshop:
    description: Открывает GUI магазина
    usage: /<command>

permissions:
  dshop.reload:
    description: Перезагрузка конфига магазина
    default: op
